version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: onekbtu
      POSTGRES_USER: onekbtuadmin
      POSTGRES_PASSWORD: UFR9Uy7EQH54p2P3bZ76


  django:
    build: ./
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - db
    ports:
      - 8000:8000
