version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: test_onekbtu
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_pass

  django:
    image: muslimbeibytuly/onekbtu-django:${TRAVIS_BRANCH}
    command: bash -c "pytest -v --cov . --cov-report term-missing --cov-fail-under=100 --flake8"
      - ./.test_env:/src/core/.env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
    depends_on:
      - db
